# -*- coding: utf-8 -*-
"""Αντίγραφο Καλώς ορίσατε στο Colab

Automatically generated by Colab.

"""

import pandas as pd

# Load the dataset
df_sample = pd.read_csv('sales_data_sample.csv', encoding='unicode_escape')

# Check for null values
null_counts = df_sample.isnull().sum()
print("Null Values per Column:")
print(null_counts[null_counts > 0])

df = pd.read_csv('sales_data_sample.csv', encoding='unicode_escape')

# Display column names and a few rows to understand the data structure
print(df.columns.tolist())
print(df.head())

import matplotlib.pyplot as plt

# Load the data
df = pd.read_csv('sales_data_sample.csv', encoding='unicode_escape')

# Group by country and sum sales
top_countries = df.groupby('COUNTRY')['SALES'].sum().sort_values(ascending=False).head(5)

# Create the plots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Bar Plot
top_countries.plot(kind='bar', ax=ax1, color='skyblue', edgecolor='black')
ax1.set_title('Top 5 Countries by Total Sales (Bar Plot)')
ax1.set_ylabel('Total Sales')
ax1.set_xlabel('Country')

# Pie Chart
top_countries.plot(kind='pie', ax=ax2, autopct='%1.1f%%', startangle=140, shadow=True, colors=['#ff9999','#66b3ff','#99ff99','#ffcc99','#c2c2f0'])
ax2.set_title('Top 5 Countries Sales Distribution (Pie Chart)')
ax2.set_ylabel('')  # Remove y-label for pie chart

plt.tight_layout()
plt.savefig('top_5_countries.png')
plt.show()

print(top_countries)

# Load the data
df = pd.read_csv('sales_data_sample.csv', encoding='unicode_escape')

# Select relevant columns
cols = ['QUANTITYORDERED', 'SALES']

# Calculate statistics
stats = pd.DataFrame({
    'Mean': df[cols].mean(),
    'Median': df[cols].median(),
    'Mode': df[cols].mode().iloc[0],  # iloc[0] in case there are multiple modes
    'Min': df[cols].min(),
    'Max': df[cols].max()
})

print(stats)

import seaborn as sns

# Load data
df = pd.read_csv('sales_data_sample.csv', encoding='unicode_escape')

# Ensure MONTH_ID is treated as a category or integer for sorting
# Aggregate sales by month
monthly_sales = df.groupby('MONTH_ID')['SALES'].sum().reset_index()

# Plotting
plt.figure(figsize=(12, 6))
sns.lineplot(data=monthly_sales, x='MONTH_ID', y='SALES', marker='o', color='darkgreen', linewidth=2.5)
plt.fill_between(monthly_sales['MONTH_ID'], monthly_sales['SALES'], color='lightgreen', alpha=0.3)

plt.title('Total Sales per Month (Trend Analysis)', fontsize=15)
plt.xlabel('Month (1=Jan, 12=Dec)', fontsize=12)
plt.ylabel('Total Sales (USD)', fontsize=12)
plt.xticks(range(1, 13))
plt.grid(True, linestyle='--', alpha=0.7)

plt.savefig('monthly_sales_trend.png')
plt.show()

# Identifying peak months
peak_months = monthly_sales.sort_values(by='SALES', ascending=False).head(3)
print(peak_months)

# Load data
df = pd.read_csv('sales_data_sample.csv', encoding='unicode_escape')

# Aggregate sales by year
yearly_sales = df.groupby('YEAR_ID')['SALES'].sum().reset_index()

# Plotting
plt.figure(figsize=(10, 6))
sns.barplot(data=yearly_sales, x='YEAR_ID', y='SALES', palette='viridis')

plt.title('Total Sales per Year', fontsize=15)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Total Sales (USD)', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.savefig('yearly_sales.png')
plt.show()

# Check monthly data for 2005 to explain the result
months_2005 = df[df['YEAR_ID'] == 2005]['MONTH_ID'].unique()
print(f"Sales data for 2005 includes months: {sorted(months_2005)}")
print(yearly_sales)

# Load data
df = pd.read_csv('sales_data_sample.csv', encoding='unicode_escape')

# Filter for 2004 and 2005
df_04 = df[df['YEAR_ID'] == 2004]
df_05 = df[df['YEAR_ID'] == 2005]

# Group by product and sum sales for each year
sales_04 = df_04.groupby('PRODUCTLINE')['SALES'].sum()
sales_05 = df_05.groupby('PRODUCTLINE')['SALES'].sum()

# Combine into a dataframe to calculate the drop
comparison = pd.DataFrame({'Sales_2004': sales_04, 'Sales_2005': sales_05})
comparison['Difference'] = comparison['Sales_2005'] - comparison['Sales_2004']

# Sort to find the biggest drop (most negative difference)
comparison_sorted = comparison.sort_values(by='Difference')

print(comparison_sorted)

# Load data
df = pd.read_csv('sales_data_sample.csv', encoding='unicode_escape')

# Count the frequency of each category
product_counts = df['PRODUCTLINE'].value_counts()

# Display the counts
print("Frequency of each Product Category:")
print(product_counts)

# Total number of unique categories
print(f"\nTotal unique categories: {len(product_counts)}")

import numpy as np

# Load the data
df = pd.read_csv('sales_data_sample.csv', encoding='unicode_escape')

# Select only numeric variables for correlation analysis
numeric_df = df.select_dtypes(include=[np.number])

# Calculate correlation matrix
corr_matrix = numeric_df.corr()

# Plotting the Heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Analysis Heatmap', fontsize=15)

plt.savefig('correlation_heatmap.png')
plt.show()

# Identify high correlations
# We exclude self-correlation (1.0) and look for values > 0.7 or < -0.7
high_corr = corr_matrix[((corr_matrix >= .7) | (corr_matrix <= -.7)) & (corr_matrix != 1.0)]
print("Variables with high correlation:")
print(high_corr.dropna(how='all', axis=0).dropna(how='all', axis=1))

"""Section B"""

# Load the three datasets for Section B
features = pd.read_csv('Features data set.csv')
sales = pd.read_csv('sales data-set.csv')
stores = pd.read_csv('stores data-set.csv')

# Convert Date to datetime for proper merging
features['Date'] = pd.to_datetime(features['Date'], dayfirst=True)
sales['Date'] = pd.to_datetime(sales['Date'], dayfirst=True)

# Merge the datasets
# First merge sales and features on Store, Date, and IsHoliday
data = pd.merge(sales, features, on=['Store', 'Date', 'IsHoliday'], how='left')

# Then merge with stores on Store
data = pd.merge(data, stores, on=['Store'], how='left')

# Check for nulls after merge
null_info = data.isnull().sum()

print("Merged Data Columns:", data.columns.tolist())
print("\nNull values in merged data:")
print(null_info[null_info > 0])
print("\nFirst 5 rows of merged data:")
print(data.head())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Load data (assuming 'data' from previous step is available)
# Re-running the merge just to be safe
features = pd.read_csv('Features data set.csv')
sales = pd.read_csv('sales data-set.csv')
stores = pd.read_csv('stores data-set.csv')
features['Date'] = pd.to_datetime(features['Date'], dayfirst=True)
sales['Date'] = pd.to_datetime(sales['Date'], dayfirst=True)
data = pd.merge(sales, features, on=['Store', 'Date', 'IsHoliday'], how='left')
data = pd.merge(data, stores, on=['Store'], how='left')

# 11. Choose Store 1 for the analysis
store_1_data = data[data['Store'] == 1].copy()

# Fill missing values for CPI and Unemployment (if any) with the mean
store_1_data['CPI'] = store_1_data['CPI'].fillna(store_1_data['CPI'].mean())
store_1_data['Unemployment'] = store_1_data['Unemployment'].fillna(store_1_data['Unemployment'].mean())

# Convert IsHoliday to numeric (0 or 1)
store_1_data['IsHoliday'] = store_1_data['IsHoliday'].astype(int)

# Features (X) and Target (y)
# We use Dept, IsHoliday, Temperature, Fuel_Price, CPI, Unemployment, Size
X = store_1_data[['Dept', 'IsHoliday', 'Temperature', 'Fuel_Price', 'CPI', 'Unemployment', 'Size']]
y = store_1_data['Weekly_Sales']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"Store 1 Regression Results:")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Model Coefficients: {dict(zip(X.columns, model.coef_))}")

"""Section C"""

# Load the advertising dataset
adv_data = pd.read_csv('advertising.csv')

# 12. Make scatter plots for all available pairs of numeric variables
# Numeric variables: 'Daily Time Spent on Site', 'Age', 'Area Income', 'Daily Internet Usage'
numeric_cols = ['Daily Time Spent on Site', 'Age', 'Area Income', 'Daily Internet Usage']

# Using pairplot to see all scatter plots at once
sns.set_style('whitegrid')
pair_plot = sns.pairplot(adv_data[numeric_cols + ['Clicked on Ad']], hue='Clicked on Ad', palette='bwr', diag_kind='kde')
pair_plot.fig.suptitle('Scatter Plots of Numeric Variables', y=1.02, fontsize=16)

plt.savefig('adv_scatter_plots.png')
plt.show()

# Calculate specific correlations for discussion
correlation_matrix = adv_data[numeric_cols].corr()
print("Correlation Matrix for Advertising Data:")
print(correlation_matrix)

# Load the advertising dataset
adv_data = pd.read_csv('advertising.csv')

# 13. Prepare data for Naïve Bayes
# Predictors (X): Numeric variables that influence clicking behavior
# Target (y): 'Clicked on Ad'

predictors = ['Daily Time Spent on Site', 'Age', 'Area Income', 'Daily Internet Usage', 'Male']
target = 'Clicked on Ad'

X = adv_data[predictors]
y = adv_data[target]

print("Predictor variables (X):")
print(X.head())
print("\nTarget variable (y):")
print(y.head())

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Reloading data to ensure variables are defined
adv_data = pd.read_csv('advertising.csv')
predictors = ['Daily Time Spent on Site', 'Age', 'Area Income', 'Daily Internet Usage', 'Male']
X = adv_data[predictors]
y = adv_data['Clicked on Ad']

# 14. Perform Naïve Bayes
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred = nb_model.predict(X_test)

# Results
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

# Visualizing Confusion Matrix
plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=['No Click', 'Click'],
            yticklabels=['No Click', 'Click'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title(f'Naïve Bayes Confusion Matrix\nOverall Accuracy: {accuracy:.2%}')
plt.savefig('nb_confusion_matrix.png')
plt.show()

print(classification_report(y_test, y_pred))